name: Feature Request
description: 아키텍처/기능 개발을 위한 이슈 템플릿
title: "[Feature] "
labels: ["feature", "planning"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✅ Feature Request
        신규 기능 또는 API 요구사항 기반 개발 이슈입니다.
        아키텍처 구조/설계 검토 후 개발에 착수하세요.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: 기능 한 줄 요약
      placeholder: ex) 좌석 조회 API 구현
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Background / Context
      description: 요구사항 ID(FR/NFR) 또는 사용자 시나리오 연결
      placeholder: ex) FR-01: 좌석 조회 기능, NFR-01: p95 500ms
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria (수용 기준)
      description: 테스트 가능하도록 구체적으로 작성
      placeholder: |
        - 특정 회차 좌석 조회 시 상태 반환
        - 캐싱 전략 적용으로 p95 500ms 이하 보장
        - Swagger 문서 자동 반영
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: Design & Decision
      description: 아키텍처/설계에 대한 간단한 결정 기록 (ADR 링크)
      placeholder: |
        - ADR-004: Redis Seat Cache Strategy 적용
        - DB 조회 최소화, TTL 기반 자동 만료
    validations:
      required: false

  - type: textarea
    id: task-list
    attributes:
      label: Tasks
      description: 체크리스트를 작성해주세요
      placeholder: |
        - [ ] Controller
        - [ ] Service
        - [ ] Repository
        - [ ] Test Code
        - [ ] Swagger Docs
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: ETC/Notes
      description: 참고 URL, 추가 논의 사항
